// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CANTalon.h"


#include "Robot.h"
#include "Acquisition.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Acquisition::Acquisition() : Subsystem("Acquisition") {
    armPiston = RobotMap::acquisitionarmPiston;
    intakeRoller = RobotMap::acquisitionintakeRoller;
}

void Acquisition::InitDefaultCommand()
{

}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Acquisition::Intake()
{
	intakeRoller->Set(0.6);
}

void Acquisition::Output()
{
	intakeRoller->Set(-0.6);
}

void Acquisition::Stop()
{
	intakeRoller->Set(0);
}
void Acquisition::RaiseArm()
{
	armPiston->Set(true);
}

void Acquisition::LowerArm()
{
	armPiston->Set(false);
}
