// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "CANTalon.h"


#include "Drive.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drive::Drive() : Subsystem("Drive") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    rDrive1 = RobotMap::driverDrive1;
    rDrive2 = RobotMap::driverDrive2;
    lDrive1 = RobotMap::drivelDrive1;
    lDrive2 = RobotMap::drivelDrive2;

    brakes = RobotMap::drivebrakes;
    gearShift = RobotMap::drivegearShift;
//    rEnc = RobotMap::driverEnc;
//    lEnc = RobotMap::drivelEnc;
    ahrs = RobotMap::driveahrs;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

}

void Drive::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

int Drive::GetLEncoderRate(){
	return lDrive1->GetEncVel();
}

int Drive::GetREncoderRate(){
	return rDrive1->GetEncVel();
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

void Drive::TankDrive(double lSpeed, double rSpeed, bool speedClosed){
	if(!speedClosed)
	{
		rDrive1->Set(rSpeed);
		rDrive2->Set(rSpeed);
		lDrive1->Set(lSpeed);
		lDrive2->Set(lSpeed);
	}
	//TODO Implement closed loop
}

void Drive::ChangeGear(bool high)
{
	gearShift->Set(high);
}

void Drive::EnableBraking()
{
	brakes->Set(true);
}

void Drive::DisableBraking()
{
	brakes->Set(false);
}

int Drive::GetLEncoder()
{
	return lDrive1->GetEncPosition();
}

int Drive::GetREncoder()
{
	return rDrive1->GetEncPosition();
}

double Drive::GetYaw()
{
	return ahrs->GetYaw();
}

bool Drive::GetGear(){
	return gearShift->Get();
}

//Should be run once everytime we
void Drive::SetControlMode(DriveControlMode cMode){
	switch (cMode)
	{
		case DriveControlMode::MotionProfile:

		break;
		case DriveControlMode::Position:
		break;
		case DriveControlMode::VelocityDriving:
		break;
		case DriveControlMode::VelocityTurning:
		break;
		case DriveControlMode::Voltage:
		break;
	};
}
