// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_H
#define DRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "AHRS.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	std::shared_ptr<CANTalon> rDrive1;
	std::shared_ptr<CANTalon> rDrive2;
	std::shared_ptr<CANTalon> lDrive1;
	std::shared_ptr<CANTalon> lDrive2;
	std::shared_ptr<Solenoid> brakes;
	std::shared_ptr<Solenoid> gearShift;
//	std::shared_ptr<Encoder> rEnc;
//	std::shared_ptr<Encoder> lEnc;
	std::shared_ptr<AHRS> ahrs;

	const double vTurnP = 0.0;
	const double vTurnI = 0.0;
	const double vTurnD = 0.0;
	const double vTurnF = 0.0;
	const double vDriveP = 0.0;
	const double vDriveI = 0.0;
	const double vDriveD = 0.0;
	const double vDriveF = 0.0;
	const double motionP = 0.0;
	const double motionI = 0.0;
	const double motionD = 0.0;
	const double motionF = 0.0;
	const double posP = 0.0;
	const double posI = 0.0;
	const double posD = 0.0;
	const double posF = 0.0;

public:
	Drive();
	void TankDrive(double lSpeed, double rSpeed, bool speedClosed = false);
	enum class DriveControlMode{
		VelocityTurning,
		VelocityDriving,
		Voltage,
		MotionProfile,
		Position
	};
	void SetControlMode(DriveControlMode cMode);
	void ChangeGear(bool high);
	bool GetGear();
	void EnableBraking();
	void DisableBraking();
	void InitDefaultCommand();
	int GetLEncoder();
	int GetREncoder();
	double GetYaw();
	int GetLEncoderRate();
	int GetREncoderRate();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};




#endif
