// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Robot.h"
#include "GearFloorAcq.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

GearFloorAcq::GearFloorAcq() : Subsystem("GearFloorAcq")
{
	storagePiston = RobotMap::floorAcqStoragePiston;
	openPiston = RobotMap::floorAcqOpenPiston;
	gearSensor = RobotMap::floorAcqSensor;
}

void GearFloorAcq::InitDefaultCommand()
{

}

void GearFloorAcq::LowerSystem()
{
	storagePiston->Set(true);
}

void GearFloorAcq::RaiseSystem()
{
	storagePiston->Set(false);
}

void GearFloorAcq::CloseSystem()
{
	storagePiston->Set(false);
}

void GearFloorAcq::OpenSystem()
{
	storagePiston->Set(true);
}

bool GearFloorAcq::GearPresent()
{
	return gearSensor->Get();
}
