// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GearFloorAcq_H
#define GearFloorAcq_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class GearFloorAcq: public Subsystem {
private:
	std::shared_ptr<Solenoid> storagePiston;
	std::shared_ptr<Solenoid> openPiston;
	std::shared_ptr<DigitalInput> gearSensor;


public:
	GearFloorAcq();
	void InitDefaultCommand();
	void LowerSystem();
	void RaiseSystem();
	void OpenSystem();
	void CloseSystem();
	bool GearPresent();
};

#endif
