// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef STORAGE_H
#define STORAGE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Storage: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	std::shared_ptr<CANTalon> ballControlMotor;
	const double storageP = 0.0;
	const double storageI = 0.0;
	const double storageD = 0.0;
	const double storageF = 0.0;

public:
	Storage();
	void InitDefaultCommand();
	void SetControlMode(CANTalon::ControlMode cMode);
	void MoveStorage();
};

#endif
